In [17]:
from lrn_sparseatt.masks import BooleanMask, SparseMask

In [18]:
m = BooleanMask.random(5, 0.6)
m.as_tensor(5)

tensor([[False,  True,  True, False, False],
        [False,  True,  True, False, False],
        [False, False, False,  True,  True],
        [ True, False, False,  True, False],
        [False, False,  True,  True, False]])

In [19]:
m.sparsity()

0.6

In [20]:
SparseMask(m.to_indices()).as_tensor(5)

tensor([[False,  True,  True, False, False],
        [False,  True,  True, False, False],
        [False, False, False,  True,  True],
        [ True, False, False,  True, False],
        [False, False,  True,  True, False]])

In [15]:
import torch
indices = torch.nonzero(m.as_tensor(5), as_tuple=False)

In [23]:
from torch.nested import nested_tensor

def boolean_mask_to_nested_indices(mask: torch.Tensor) -> nested_tensor:
    """
    Convert a boolean mask of shape (T, T) to a nested list of indices where each sublist corresponds to the True values in each row of the mask.

    Args:
        mask (torch.Tensor): A boolean tensor of shape (T, T).
    Returns:
        nested_tensor: A nested tensor where the outer list has length T and each inner list contains the column indices of the True values in the corresponding row of the input mask.
    """
    nested_indices = []
    for i in range(mask.size(0)):
        true_indices = torch.nonzero(mask[i], as_tuple=False).flatten()
        nested_indices.append(true_indices)
    nested_indices = nested_tensor(nested_indices, layout=torch.jagged)
    return nested_indices

In [25]:
nt = boolean_mask_to_nested_indices(m.as_tensor(5))
[comp for comp in nt]

[tensor([1, 2]),
 tensor([1, 2]),
 tensor([3, 4]),
 tensor([0, 3]),
 tensor([2, 3])]